### ISSUE TITLE
[Suggestion] Handling of offline/not supported pools

### ISSUE THREAD

**Issue by yamiM0NSTER** [ZedPea/turtlecoin-pool-bot#2]
The bot could list these pools at end of /heights and exclude from the /forked list (maybe /down list or something along the lines + cache of last block if any existed)

**Comment by zpalmtree** [comment]
This is basically what the api down bit does, I think. Atm it will just ignore pools of an unknown type, could possibly list them but there's not much utility in that, I don't think. (And there aren't any unsupported pools atm)
